version: "3.9"

networks:
  pipeline-net:
    driver: bridge

services:
  ingestion:
    build: ./ingestion
    container_name: phase-ingestion
    networks: [pipeline-net]
    ports: ["8001:8000"]
    environment:
      NEXT_SERVICE: http://input-validation:8000

  input-validation:
    build: ./input-validation
    container_name: phase-input
    networks: [pipeline-net]
    ports: ["8002:8000"]
    environment:
      NEXT_SERVICE: http://model:8000

  model:
    build: ./model
    container_name: phase-model
    networks: [pipeline-net]
    ports: ["8003:8000"]
    environment:
      NEXT_SERVICE: http://output:8000

  output:
    build: ./output
    container_name: phase-output
    networks: [pipeline-net]
    ports: ["8004:8000"]
